apiVersion: v1
kind: Service
metadata:
  name: leave-management-service
spec:
  selector:
    app: leave-management
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer